### ISSUE TITLE
docker版文件索引和搜索无法正常使用

### ISSUE THREAD

**Issue by babyfenei** [helloxz/docker-zdir#1]
![image](https://user-images.githubusercontent.com/22876759/96270481-4fcee100-0ffe-11eb-83b2-47e3ade96e46.png)

**Comment by helloxz** [comment]
检查下挂载目录的权限是否正确呢，如果还是不行加我QQ看下：337003006

**Comment by helloxz** [comment]
您好，此问题已经修复，请删除原来的容器，然后重新部署一次。
